# Generated by Django 4.1.6 on 2023-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_book_balance_history_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
